// This file is generated by Slice Machine. Update with care!

import Code from './Code';
import Image from './Image';
import Quote from './Quote';
import TextBlock from './TextBlock';

export {
	Code,
	Image,
	Quote,
	TextBlock,
};

export const components = {
	code: Code,
	image: Image,
	quote: Quote,
	text_block: TextBlock,
};
