// This file is generated by Slice Machine. Update with care!

import Image from "./Image";
import Quote from "./Quote";
import TextBlock from "./TextBlock";

export { Image, Quote, TextBlock };

export const components = {
  image: Image,
  quote: Quote,
  text_block: TextBlock,
};
